import { WeaponGroup, WeaponTrait } from "./types.ts";
declare const WEAPON_CATEGORIES: readonly ["unarmed", "simple", "martial", "advanced"];
declare const WEAPON_GROUPS: Set<
    | "mental"
    | "poison"
    | "sonic"
    | "axe"
    | "bomb"
    | "bow"
    | "brawling"
    | "club"
    | "corrosive"
    | "crossbow"
    | "cryo"
    | "dart"
    | "firearm"
    | "flail"
    | "flame"
    | "grenade"
    | "hammer"
    | "knife"
    | "laser"
    | "pick"
    | "plasma"
    | "polearm"
    | "projectile"
    | "shield"
    | "shock"
    | "sling"
    | "sniper"
    | "spear"
    | "sword"
>;
declare const MELEE_WEAPON_GROUPS: Set<"axe" | "brawling" | "club" | "dart" | "flail" | "hammer" | "knife" | "pick" | "polearm" | "shield" | "spear" | "sword">;
/** Groups that will be forced as ranged weapons */
declare const MANDATORY_RANGED_GROUPS: Set<WeaponGroup>;
declare const WEAPON_PROPERTY_RUNE_TYPES: Set<
    | "holy"
    | "unholy"
    | "vorpal"
    | "corrosive"
    | "shock"
    | "anchoring"
    | "astral"
    | "speed"
    | "ancestralEchoing"
    | "ashen"
    | "authorized"
    | "bane"
    | "bloodbane"
    | "bloodthirsty"
    | "bolkasBlessing"
    | "brilliant"
    | "called"
    | "coating"
    | "conducting"
    | "crushing"
    | "cunning"
    | "dancing"
    | "deathdrinking"
    | "decaying"
    | "demolishing"
    | "disrupting"
    | "earthbinding"
    | "energizing"
    | "extending"
    | "fanged"
    | "fearsome"
    | "flaming"
    | "flickering"
    | "flurrying"
    | "frost"
    | "ghostTouch"
    | "giantKilling"
    | "greaterGiantKilling"
    | "greaterAnchoring"
    | "greaterAshen"
    | "greaterAstral"
    | "greaterBloodbane"
    | "greaterBolkasBlessing"
    | "greaterBrilliant"
    | "greaterCorrosive"
    | "greaterCrushing"
    | "greaterDecaying"
    | "greaterDisrupting"
    | "greaterExtending"
    | "greaterFanged"
    | "greaterFearsome"
    | "greaterFlaming"
    | "greaterFrost"
    | "greaterHauling"
    | "greaterImpactful"
    | "greaterKolssOath"
    | "greaterRooting"
    | "greaterShock"
    | "greaterThundering"
    | "greaterTruddsStrength"
    | "grievous"
    | "hauling"
    | "hopeful"
    | "hooked"
    | "impactful"
    | "impossible"
    | "keen"
    | "kinWarding"
    | "kolssOath"
    | "majorFanged"
    | "majorRooting"
    | "merciful"
    | "nightmare"
    | "pacifying"
    | "returning"
    | "rooting"
    | "serrating"
    | "shifting"
    | "shockwave"
    | "spellStoring"
    | "swarming"
    | "thundering"
    | "truddsStrength"
    | "trueRooting"
    | "underwater"
    | "wounding"
>;
declare const THROWN_RANGES: Set<10 | 40 | 20 | 30 | 15 | 80 | 100 | 60>;
declare const WEAPON_RANGES: Set<10 | 40 | 20 | 30 | 50 | 15 | 80 | 100 | 120 | 240 | 60 | 70 | 90 | 110 | 140 | 150 | 180 | 200 | 300>;
declare const RANGED_ONLY_TRAITS: Set<WeaponTrait>;
declare const MELEE_ONLY_TRAITS: Set<WeaponTrait>;
export {
    MANDATORY_RANGED_GROUPS,
    MELEE_ONLY_TRAITS,
    MELEE_WEAPON_GROUPS,
    RANGED_ONLY_TRAITS,
    THROWN_RANGES,
    WEAPON_CATEGORIES,
    WEAPON_GROUPS,
    WEAPON_PROPERTY_RUNE_TYPES,
    WEAPON_RANGES,
};
