declare const CONSUMABLE_CATEGORIES: Set<
    | "poison"
    | "wand"
    | "catalyst"
    | "elixir"
    | "fulu"
    | "gadget"
    | "mutagen"
    | "oil"
    | "potion"
    | "scroll"
    | "snare"
    | "talisman"
    | "drug"
    | "other"
    | "toolkit"
>;
declare const DAMAGE_OR_HEALING_CONSUMABLE_CATEGORIES: Set<
    | "poison"
    | "wand"
    | "catalyst"
    | "elixir"
    | "fulu"
    | "gadget"
    | "mutagen"
    | "oil"
    | "potion"
    | "scroll"
    | "snare"
    | "talisman"
    | "drug"
    | "other"
    | "toolkit"
>;
declare const DAMAGE_ONLY_CONSUMABLE_CATEGORIES: Set<
    | "poison"
    | "wand"
    | "catalyst"
    | "elixir"
    | "fulu"
    | "gadget"
    | "mutagen"
    | "oil"
    | "potion"
    | "scroll"
    | "snare"
    | "talisman"
    | "drug"
    | "other"
    | "toolkit"
>;
export { CONSUMABLE_CATEGORIES, DAMAGE_ONLY_CONSUMABLE_CATEGORIES, DAMAGE_OR_HEALING_CONSUMABLE_CATEGORIES };
