name: PF2e/Foundry Types CI

on:
    push:
        branches:
            - v13
    pull_request:
        branches:
            - v13

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              id: checkout

            - uses: actions/setup-node@v4
              id: setup-node
              with:
                  cache: npm
                  cache-dependency-path: package-lock.json

            - if: ${{ steps.setup-node.outputs.cache-hit != 'true' }}
              run: npm ci

            - run: npm run tsc

            - run: npm run eslint
